name: Tag version

on:
  push:
    branches:
      - main

jobs:
  tag-release:
    name: Tag release
    env:
      COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
    if: ${{ github.event_name == 'push' && !contains(join(github.event.head_commit.message), '#skip') }}
    needs: [simple_tests]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@ce4b5ffa38e072fa7a901e417253c438fcc2ccce
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
